version: "3.7"

# volumes:
#   mariadb:
#     driver: local

# networks:
#     db:
#         driver: bridge

services:
  # mariadb:
  #   image: mariadb:latest
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_USER:  admin 
  #     MYSQL_PASSWORD: admin
  #   expose:
  #       - "40000"
  #   ports:
  #       - "40000:3306"
  #   volumes:
  #    - mariadb:/var/lib/mysql
  #   networks:
  #     db:
              
  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "40001"
      - "3306"
    ports:
      - "40001:80"
      # - "3306:3306"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306 
    # networks:
    #   db: